version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /desktop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /desktop-volunteer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /brokerapi
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /connectcore
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /punchcore
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /wsscore
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /desktop/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /desktop-volunteer/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /deploy/relay
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /deploy/broker
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /deploy/relayhub
    schedule:
      interval: weekly
